In [2]:
# 这里，布尔索引的作用是，根据'Bob',找到他的每条信息。根据结果知道，'Bob'的信息有两条。
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [6]:
data = np.random.randn(7, 4)
data

array([[ 1.40540371, -2.71551847,  0.38503483,  0.701648  ],
       [ 0.78450099, -0.74606018, -0.93093824,  0.36927797],
       [ 0.05314527,  0.30154865, -0.37456499,  1.63503227],
       [-0.14329374,  0.14385545,  0.26838173, -1.14855697],
       [ 1.22534951,  0.10691372, -0.71505506, -0.09633539],
       [-0.05027374,  0.40602133,  0.82676533, -0.30099985],
       [ 1.27916904, -1.33977678, -0.21369588, -0.52228655]])

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Bob']

array([[ 1.40540371, -2.71551847,  0.38503483,  0.701648  ],
       [-0.14329374,  0.14385545,  0.26838173, -1.14855697]])

In [9]:
# 用切片或整数值对布尔值数组进行混合和匹配。

In [10]:
data[names == 'Bob', 2:]

array([[ 0.38503483,  0.701648  ],
       [ 0.26838173, -1.14855697]])

In [11]:
# （取反）选择除了‘Bob’以外的其他数据

In [12]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [15]:
data[~(names == 'Bob')]

array([[ 0.78450099, -0.74606018, -0.93093824,  0.36927797],
       [ 0.05314527,  0.30154865, -0.37456499,  1.63503227],
       [ 1.22534951,  0.10691372, -0.71505506, -0.09633539],
       [-0.05027374,  0.40602133,  0.82676533, -0.30099985],
       [ 1.27916904, -1.33977678, -0.21369588, -0.52228655]])